apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-cat-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dog-cat-classifier
  template:
    metadata:
      labels:
        app: dog-cat-classifier
    spec:
      containers:
      - name: dog-cat-classifier
        image: fikri917/dogandcat:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        env:
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        - name: FLASK_RUN_PORT
          value: "5000"  # Opsional, jika Anda ingin memastikan Flask menggunakan port tertentu
