apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-cat-classifier
spec:
  replicas: 3  # Gunakan 3 pod untuk ketersediaan tinggi
  selector:
    matchLabels:
      app: dog-cat-classifier
  template:
    metadata:
      labels:
        app: dog-cat-classifier
    spec:
      containers:
      - name: dog-cat-classifier
        image: fikri917/dogandcat:latest  # Ganti dengan nama image Docker Anda
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dog-cat-classifier-service
spec:
  selector:
    app: dog-cat-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
