apiVersion: v1
kind: Service
metadata:
  name: dog-cat-classifier-service
spec:
  selector:
    app: dog-cat-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 31034  # Port yang digunakan pada node
  type: NodePort
