apiVersion: v1
kind: Service
metadata:
  name: dog-cat-classifier
spec:
  selector:
    app: dog-cat-classifier
  ports:
    - protocol: TCP
      port: 5000  # Sesuaikan dengan port aplikasi Anda
      targetPort: 5000
  type: NodePort  # Gunakan ClusterIP, NodePort, atau LoadBalancer sesuai kebutuhan
