apiVersion: v1
kind: Service
metadata:
  name: dog-cat-classifier
spec:
  selector:
    app: dog-cat-classifier
  ports:
    - protocol: TCP
      port: 8080  # Sesuaikan dengan port aplikasi Anda
      targetPort: 8080
  type: LoadBalancer  # Gunakan ClusterIP, NodePort, atau LoadBalancer sesuai kebutuhan
