name: CI/CD Pipeline

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: Run Super Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push Docker Image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: fikri917/dogandcat:latest

    - name: Run Docker Container
      run: docker run -d -p 5000:5000 fikri917/dogandcat:latest
